### ISSUE TITLE
'Shared Data Model' via 'Hierarchy of Standard Ontologies'

### ISSUE THREAD

**Issue by jimschoening1** [dtinit/portability-articles#18]
1. Chris Riley envisions a 'shared data model' in his 28 Aug 2023 Blog at https://dtinit.org/blog/2023/08/28/data-is-binary-but.  This would be a hub model that any disparate source data can be mapped to, and then mapped again to any disparate destination data model. 

2. Traditional data models (e.g., schema.org) have not and cannot (even in theory) scale to achieve this vision; however,...

3. A potentially viable solution is a 'hierarchy of standard ontologies,' which this issue proposes.  This approach will be pursued in parallel to the current DTI strategy of point-to-point interfaces and multiple vertical standards, which is a good way to get started but the number of mappings grows exponentially with the number of sources, destinations, and data standards.  Using standards such as VCARD delays but doesn't solve the scaling challenge.  This proposed ontology strategy grows linearly, so it can scale.  

4. This approach will start with existing standard and draft standard ontologies described below and cover the same data elements as current DTI interfaces, to include VCARD data elements, calendar entities, and meta data from pictures, videos, and social media posts. Eventually, as the number of disparate data sources, target data receivers, and data standards grow too big to manage, this hub-and-spoke approach should become the only viable approach.  

5. Hierarchy of Standard Ontologies:  
     a. Top-Level Ontology:	ISO/IEC-JTC1-21838-2 Basic Formal Ontology.   Small ontology providing structure from which mid-level ontology extends. See https://ncorwiki.buffalo.edu/index.php/BFO_2020, https://ontobee.org/, and https://www.iso.org/standard/74572.html.
     b. Mid-Level Ontology:	P3195.1 Common Core Ontology (CCO). Large ontology of classes common to multiple domains, and from which all domains extend.  See https://github.com/CommonCoreOntology/CommonCoreOntologies 
     c. Domain Ontologies: 	P3195.1.1 Cyber Ontology. https://opensource.ieee.org/cyber-ontology-working-group    
     d. P3195.1.2 Person Ontology    https://opensource.ieee.org/person-ontology-group/person-ontology-project/-/blob/master/dev/Person-Ontology-dev.ttl
     e. P3195.1._   (Many more domain ontologies to follow.)
     f. Application Ontologies   These may or may not be standards. They draw classes from any of the above ontologies, which maintain logically consistency and don't lap because of the hierarchy.  An example of this is the PDM Glossary in next paragraph. 
 
6. Glossaries for Ease of Use:
	Ontologies can be packaged as glossaries for easier use by developers.  A glossary provides typical terms and definitions, but also links to ontologies for logically consistent semantics.  Glossary terms and definitions can easily (even automatically) be translated into other human languages without changing the underlying ontologies. An example of a 308-term glossary contributed to MyData.org #standard-personal-data-model is Personal Data Model (PDM) Glossary at https://docs.google.com/spreadsheets/d/1KAuEoUG5zMgaV7FkForZatBKiAHHTxFR/edit#gid=2105800037.  

7. Next Steps:
     a. Feedback is needed on this issue, including questions, comments, or constructive criticism.  Without feedback, it will be hard to motivate contributors to proceed.  
     b. Explore any next steps proposed by stakeholders
     c. Merge VCARD data elements into the above hierarchy of ontologies and conduct an end-to-end demo that matches direct use of VCARD.  (Note: To match results will not be enough to justify adoption at this time.)
     d. Repeat step 3 for other data and meta data models and data standards.       

Respectfully Submitted:
Jim Schoening
Chair, IEEE Ontology Standards Working Group, https://sagroups.ieee.org/oswg/ 
Member MyData Global, Slack Channel #standard-personal-data-model at https://mydataglobal.slack.com/archives/C04DUMBU4E4, https://github.com/standard-personal-data-model
Lead, Linux Foundation Integrated Personal Data Store (iPDS) https://github.com/integrated-personal-data-system. See video of tech demo at https://drive.google.com/file/d/1c95ESkIL5N5ASNZGza5TOg3okkfHBnUB/view?usp=sharing

**Comment by lisad** [comment]
Thanks, but this is a whole set of projects and several orders of magnitude beyond the scope of an issue for this project, which is concerned with public documentation and help articles.

**Comment by jimschoening1** [comment]
Lisa, Did you see my email?  Is there a place I can post this contribution.
