### ISSUE TITLE
Fix formatting of list in "Apple iCloud photos to Google Photos

### ISSUE THREAD

**Issue by alexbainter** [dtinit/portability-articles#29]
See "What this solution does not do"

![image](https://github.com/dtinit/portability-articles/assets/6510436/5384c7b9-816d-4162-b3f6-77befe9444a2)

**Comment by aaronjae22** [comment]
Can I do this one?

**Comment by alexbainter** [comment]
Turns out this wasn't a formatting issue, see https://github.com/dtinit/portmap/issues/94
